CREATE TABLE IF NOT EXISTS Tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  deadline DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);